// Generated by CoffeeScript 1.6.3
(function() {
  var UIDialog;

  UIDialog = (function() {
    UIDialog.parent = null;

    UIDialog.count = 0;

    UIDialog.byId = {};

    UIDialog.prototype.button = {};

    function UIDialog(opts) {
      var b, body, btn, foot, head, k, section, show, v, _ref, _ref1;
      if (opts == null) {
        opts = {};
      }
      this.parent = opts.parent, this.id = opts.id, this.init = opts.init, show = opts.show, head = opts.head, foot = opts.foot, body = opts.body;
      if (this.parent == null) {
        this.parent = UIDialog.parent;
      }
      if (this.id == null) {
        this.id = "dialog-" + (UIDialog.count++);
      }
      this.parent.append("<div class=\"dialog\" id=\"" + this.id + "\">\n  <div class=\"dlg-head\"></div>\n  <div class=\"dlg-body\"></div>\n  <div class=\"dlg-foot\"></div>\n</div>");
      this.query = this.$ = $("#" + this.id);
      _ref = {
        head: head,
        body: body,
        foot: foot
      };
      for (section in _ref) {
        v = _ref[section];
        if (!(v != null)) {
          continue;
        }
        this[section] = $("#" + this.id + " .dlg-" + section);
        if (v.html != null) {
          this[section].append(v.html);
        }
        if (v.buttons != null) {
          _ref1 = v.buttons;
          for (k in _ref1) {
            b = _ref1[k];
            b.id = k;
            b.parent = this[section];
            btn = new UIButton(b);
            this.button[k] = btn;
          }
        }
      }
      if ((this.init != null) && typeof this.init === "function") {
        this.init();
      }
      if (show === true) {
        this.show();
      }
    }

    UIDialog.prototype.hide = function() {
      return this.show(false);
    };

    UIDialog.prototype.show = function(show) {
      var state;
      if (show == null) {
        show = true;
      }
      state = show ? 'block' : 'none';
      this.parent.css('display', state);
      return this.query.css('display', state);
    };

    return UIDialog;

  })();

  $(document).ready(function() {
    $('body').append("<div class=\"dialog-container\"></div>");
    UIDialog.parent = $('body > .dialog-container');
    return true;
  });

  window.UIDialog = UIDialog;

}).call(this);
