// Generated by CoffeeScript 1.6.3
(function() {
  var UITask,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  UITask = (function() {
    UITask.container = null;

    function UITask(opts) {
      var call, progress, _i, _len, _ref,
        _this = this;
      if (opts == null) {
        opts = {};
      }
      this.hide = __bind(this.hide, this);
      this.show = __bind(this.show, this);
      this.parent = opts.parent, this.id = opts.id, this.title = opts.title, progress = opts.progress;
      if (this.parent == null) {
        this.parent = Task.container;
      }
      if (typeof this.parent === "string") {
        this.parent = $(this.parent);
      }
      this.parent.append("<div class=\"task\">\n  <div class=\"progress\"></div>\n  <h4>" + this.title + "</h4>\n  <button class=\"close click\">close</button>\n</div>");
      this.query = this.$ = this.parent.find(".task");
      this.close = this.query.find("button.close");
      this.close.on('click', function() {
        return _this.query.css("display", "none");
      });
      _ref = ['pause', 'cancel', 'resume'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        call = _ref[_i];
        if (opts[call] != null) {
          this.query.append("<button class=\"framed " + call + "\" />");
          this[call] = this.query.find('.' + call);
          this[call].on('click', function() {
            return call();
          });
        }
      }
      this.pbar = this.query.find(".progress");
      this.tbar = this.query.find("h4");
      if (progress != null) {
        this.progress(progress, state);
      }
    }

    UITask.prototype.show = function() {
      return this.query.show();
    };

    UITask.prototype.hide = function() {
      return this.query.hide();
    };

    UITask.prototype.progress = function(v, k) {
      this.tbar.html(this.title + (k != null ? ' [' + k + ']' : ''));
      return this.pbar.css("width", '' + Math.min(100, v) + '%');
    };

    UITask.prototype.done = function() {
      return this.pbar.css('background', 'green');
    };

    return UITask;

  })();

  $(document).ready(function() {
    $('body').append("<div class=\"task-container noselect noclick\"></div>");
    Task.container = $('body > .task-container');
    return true;
  });

  window.UITask = UITask;

}).call(this);
